# Generated by Django 3.1.7 on 2021-03-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diligencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diligencia',
            options={'verbose_name': 'Diligência', 'verbose_name_plural': 'Diligências'},
        ),
    ]
